# NumPy [Numerical Python]

pip install numpy - pip used to install python packages

In [6]:
import numpy as np

numpy library in Python that allow you to work with  large, multi-dimensional arrays and matrices with the help of mathematical functions.

In [12]:
oneD = np.array([1, 2, 3])

In [14]:
print(oneD)

[1 2 3]


In [15]:
oneD+10

array([11, 12, 13])

In [16]:
print(oneD)

[1 2 3]


In [19]:
twoD = np.array([[1,2],[3,4]])

In [20]:
twoD + 10

array([[11, 12],
       [13, 14]])

In [21]:
np.dot(twoD, np.array([[1,2],[3,4]]) )

array([[ 7, 10],
       [15, 22]])